name: Trigger Vercel Rebuild Every 3 Hours

on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:       # Optional: allow manual trigger

jobs:
  trigger-vercel-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Deploy Hook
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
